name: Tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        os: [x86_64-unknown-linux-musl, arm-unknown-linux-musleabihf]
        runs-on: [ubuntu-latest]
        cross: [true]
        include:
          - os: x86_64-apple-darwin
            runs-on: macos-latest # Apple needs to be compiled on an apple os
            cross: false # Cross fails on these platforms
          - os: x86_64-pc-windows-gnu
            runs-on: windows-latest # Not needed, but why not?
            suffix: .exe # Windows has an .exe suffix
            cross: false # Cross fails on these platforms

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: ${{ matrix.os }}

      - name: Tests
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          use-cross: ${{ matrix.cross }}
          command: test
          args: --target ${{ matrix.os }} --verbose

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy
          target: x86_64-unknown-linux-musl
      - uses: actions-rs/clippy-check@b5b5f21f4797c02da247df37026fcd0a5024aa4d # v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --target x86_64-unknown-linux-musl
